---
# defaults file for leanbit.netdata
netdata_install_dir: /opt
netdata_systemd: True
netdata_deps:
  - zlib1g-dev
  - uuid-dev
  - libmnl-dev
  - gcc
  - make
  - autoconf
  - autoconf-archive
  - autogen
  - automake
  - pkg-config
netdata_version: v1.8.0