---

- name: Wubba
  unarchive:
    src: 'https://wordpress.org/latest.zip'
    dest: /var/www/html
    remote_src: yes

- name: lubba
  copy: src=/vagrant/useful/wordpress/wp-config.php dest=/var/www/html/wordpress/wp-config.php owner=www-data

- name: dubdub
  file:
    path: /var/www/html/wordpress
    state: directory
    mode: 0755
    group: www-data
    owner: root
    recurse: yes

- name: move the content
  copy: src=/vagrant/useful/wordpress/wp-content/ dest=/var/www/html/wordpress/wp-content owner=www-data
